### ISSUE TITLE
Raw2Raw with the same cameras, but from different angles

### ISSUE THREAD

**Issue by Alexasandrovich** [mahmoudnafifi/raw2raw#1]
Hi! Can you please help me with one question: I have two cameras that shoot panorama and there is a problem in color correction due to different lighting and automatic tonemapping. I decided to deal with this problem through mapping raw colors from one image to the other. How much of your solution is suitable for this? Or maybe there are some tips. Thanks in advance!

**Comment by mahmoudnafifi** [comment]
I guess this paper doesn't fit well with your problem. You may think of using chromatic adaptation to deal with different lighting conditions -- here I am assuming that you have an accurate white-balance information for each frame. Definitely working on raw space is better; at least it will solve the issue on tone mapping you faced when processing camera-rendered frames instead.

**Comment by Alexasandrovich** [comment]
Thank you so much, you gave me a very interesting idea for development!
