### ISSUE TITLE
About raw2raw dataset

### ISSUE THREAD

**Issue by DY112** [mahmoudnafifi/raw2raw#2]
Hello, I'm interested in your dataset, and here is some questions about your dataset.

- There is no matching image in samsung-s9 directory with respect to 'iphone-x/dng/2021-06-03_21-05-34.dng' file.
Is there no matching samsung data?

- Also, in your paper, "115 pairs of images are provided as a paired set", but there are only 68 pairs in the dataset that I downloaded. Is there something I misunderstood?

- If you know of a dataset that provides raw-sRGB pairs for two or more cameras in a raw format file with metadata, not png, can you please let me know? (The conversion matrix must be computable to other camera RAW formats, including color charts within the image)

**Comment by DY112** [comment]
Oh, after I run the script, I fully understood the composition of your dataset.
Can you just give me some advice on the last question?

**Comment by DY112** [comment]
Oh, after I run the script, I fully understood the composition of your dataset.
Can you just give me some advice on the last question?

**Comment by mahmoudnafifi** [comment]
Hi @DY112, thanks for your interest in the work. You can check [NUS dataset](https://cvil.eecs.yorku.ca/projects/public_html/illuminant/illuminant.html) for raw-sRGB pairs for 8 different cameras.

**Comment by DY112** [comment]
Thank you, @mahmoudnafifi !
I'll check about the dataset.

Have a great day 😁
